/**
* Head include
* ------------------
* css & script 공통 include
*/

(function(){
	var str=''
		+''
		+'<div class="subNavi_inner">'
	    +'		<ul class="subNaviList">'
	    +'			<li class="subMenu-dash active"><a href="#none"><span>대시보드</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li class="active"><a href="#none">대시보드</a></li>'
	    +'					<li><a href="#none">농장산책_웹</a></li>'
	    +'					<li><a href="#none">농장산택_컨설턴트</a></li>'
	    +'					<li><a href="#none">사이트맵</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-data"><a href="#none"><span>데이터조회</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">수집데이터 조회</a></li>'
	    +'					<li><a href="#none">영농환경 분석</a></li>'
	    +'					<li><a href="#none">병해충이력 조회</a></li>'
	    +'					<li><a href="#none">데이터 수집률 조회</a></li>'
	    +'					<li><a href="#none">농장별 통신이력 조회</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-grow"><a href="#none"><span>생육/선별정보</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">생육조사기준정보</a></li>'
	    +'					<li><a href="#none">생육조사정보조회</a></li>'
	    +'					<li><a href="#none">생육조사(컬티랩스)조회</a></li>'
	    +'					<li><a href="#none">생육조사정보등록</a></li>'
	    +'					<li><a href="#none">생육사진정보조회</a></li>'
	    +'					<li><a href="#none">선별정보조회</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-facilities"><a href="#none"><span>시설제어</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">시설제어</a></li>'
	    +'					<li><a href="#none">임계값설정</a></li>'
	    +'					<li><a href="#none">이상값관리</a></li>'
	    +'					<li><a href="#none">기준장비관리</a></li>'
	    +'					<li><a href="#none">설치장비관리</a></li>'
	    +'					<li><a href="#none">촬영시간관리</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-pls"><a href="#none"><span>PLS</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">병충해발생예측</a></li>'
	    +'					<li><a href="#none">방제약제추천</a></li>'
	    +'					<li><a href="#none">병해충정보관리</a></li>'
	    +'					<li><a href="#none">병해충별방제약제관리</a></li>'
	    +'					<li><a href="#none">방제약제교차저항성관리</a></li>'
	    +'					<li><a href="#none">PLS기준정보설정</a></li>'
	    +'					<li><a href="#none">방제약제Profile관리</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-consulting"><a href="#none"><span>컨설팅관리</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">일정관리</a></li>'
	    +'					<li><a href="#none">컨설팅입력</a></li>'
	    +'					<li><a href="#none">컨설팅조회</a></li>'
	    +'					<li><a href="#none">A/S관리</a></li>'
	    +'					<li><a href="#none">데이터컨설팅</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-images"><a href="#none"><span>이미지수집가공</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">이미지관리</a></li>'
	    +'					<li><a href="#none">작업관리</a></li>'
	    +'					<li><a href="#none">검수관리</a></li>'
	    +'					<li><a href="#none">데이터조회</a></li>'
	    +'					<li><a href="#none">통계</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-sms"><a href="#none"><span>문자발송관리</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">하위메뉴1</a></li>'
	    +'					<li><a href="#none">하위메뉴2</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-farm"><a href="#none"><span>농장관리</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">하위메뉴1</a></li>'
	    +'					<li><a href="#none">하위메뉴2</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-info"><a href="#none"><span>영농정보</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">유통정보</a></li>'
	    +'					<li><a href="#none">영농정보조회</a></li>'
	    +'					<li><a href="#none">컨설팅관리</a></li>'
	    +'					<li><a href="#none">부계정관리</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-user"><a href="#none"><span>사용자관리</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">사용자관리</a></li>'
	    +'					<li><a href="#none">그룹관리</a></li>'
	    +'					<li><a href="#none">그룹별사용자관리</a></li>'
	    +'					<li><a href="#none">그룹별메뉴권한관리</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-system"><a href="#none"><span>시스템관리</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">공지사항관리</a></li>'
	    +'					<li><a href="#none">메뉴관리</a></li>'
	    +'					<li><a href="#none">프로그램정보</a></li>'
	    +'					<li><a href="#none">코드정보</a></li>'
	    +'					<li><a href="#none">품목정보</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'			<li class="subMenu-control"><a href="#none"><span>통합관제관리</span></a>'
	    +'				<ul class="subNaviList_dep2">'
	    +'					<li><a href="#none">기관관리</a></li>'
	    +'					<li><a href="#none">URL관리</a></li>'
	    +'					<li><a href="#none">기관별메뉴관리</a></li>'
	    +'					<li><a href="#none">기관별/그룹별메뉴권한관리</a></li>'
	    +'					<li><a href="#none">기관별/그룹별사용자관리</a></li>'
	    +'					<li><a href="#none">기관별코드관리</a></li>'
	    +'					<li><a href="#none">기준코드관리</a></li>'
	    +'					<li><a href="#none">로그인화면관리</a></li>'
	    +'					<li><a href="#none">기관별화면관리</a></li>'
	    +'					<li><a href="#none">기관별그룹관리</a></li>'
	    +'					<li><a href="#none">기관별사용자관리</a></li>'
	    +'					<li><a href="#none">기관별품목관리</a></li>'
	    +'					<li><a href="#none">기준프로그램관리</a></li>'
	    +'					<li><a href="#none">기준품목관리</a></li>'
	    +'				</ul>'
	    +'			</li>'
	    +'		</ul>'
	    +'	</div>'
	;

	document.write(str);
})();